2021-03-10 15:37:56.000   impfterminservice   [suc] [*PV9C]   Terminpaar gefunden!
2021-03-10 15:38:06.000   impfterminservice   [suc] [*PV9C]   Termin erfolgreich gebucht!
2021-04-30 12:55:40.045   impfterminservice   [err] [*A ]   Kein Impfzentrum in PLZ a verf√ºgbar
2021-04-30 20:54:09.025   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:54:09.052   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:54:09.080   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:54:09.112   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:54:09.140   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:54:09.172   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:54:09.198   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:54:09.224   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:54:09.255   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:54:09.289   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:54:09.291   impfterminservice   [err] [*A ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:54:18.910   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:54:18.942   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:54:18.965   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:54:18.988   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:54:19.018   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:54:19.046   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:54:19.072   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:54:19.098   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:54:19.123   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:54:19.150   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:54:19.152   impfterminservice   [err] [*A ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:54:53.165   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:54:53.195   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:54:53.226   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:54:53.259   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:54:53.292   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:54:53.325   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:54:53.349   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:54:53.382   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:54:53.407   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:54:53.438   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:54:53.440   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:55:36.841   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:55:36.862   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:55:36.889   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:55:36.918   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:55:36.939   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:55:36.968   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:55:36.990   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:55:37.025   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:55:37.048   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:55:37.071   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:55:37.072   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:56:35.370   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:56:35.394   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:56:35.425   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:56:35.446   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:56:35.473   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:56:35.493   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:56:35.522   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:56:35.548   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:56:35.582   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:56:35.606   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:56:35.607   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:57:39.489   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:57:39.512   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:57:39.535   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:57:39.565   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:57:39.587   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:57:39.614   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:57:39.635   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:57:39.666   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:57:39.691   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:57:39.727   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:57:39.729   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:59:13.372   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:59:13.399   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:59:13.426   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:59:13.452   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:59:13.481   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:59:13.508   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:59:13.536   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:59:13.565   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:59:13.593   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:59:13.624   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:59:13.626   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 20:59:43.264   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 20:59:43.299   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 20:59:43.332   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 20:59:43.365   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 20:59:43.398   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 20:59:43.427   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 20:59:43.459   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 20:59:43.491   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 20:59:43.521   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 20:59:43.551   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 20:59:43.553   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 21:00:55.396   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 1
2021-04-30 21:00:55.429   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 2
2021-04-30 21:00:55.455   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 3
2021-04-30 21:00:55.483   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 4
2021-04-30 21:00:55.522   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 5
2021-04-30 21:00:55.548   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 6
2021-04-30 21:00:55.579   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 7
2021-04-30 21:00:55.607   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 8
2021-04-30 21:00:55.640   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 9
2021-04-30 21:00:55.675   impfterminservice   [err] [impfzentren_laden]   JSONDecodeError exception raised - retry 10
2021-04-30 21:00:55.678   impfterminservice   [err] [*ZKFX]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-04-30 21:14:56.804   impfterminservice   [err] [cookies_erneuern]   StaleElementReferenceException exception raised - retry 1
2021-05-01 00:16:15.097   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:16:15.099   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:16:15.099   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:17:15.145   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:17:15.146   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:17:15.146   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:18:15.186   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:18:15.187   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:18:15.187   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:19:15.228   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:19:15.229   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:19:15.230   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:20:15.278   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:20:15.278   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:20:15.279   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:21:15.324   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:21:15.325   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:21:15.325   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:22:15.363   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:22:15.364   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:22:15.364   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:23:15.397   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:23:15.397   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:23:15.398   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:24:15.448   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:24:15.449   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:24:15.449   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:25:15.478   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:25:15.478   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:25:15.479   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:26:15.573   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:26:15.573   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:26:15.574   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:27:15.616   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:27:15.617   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:27:15.617   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:28:15.756   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:28:15.757   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:28:15.757   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:29:15.796   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:29:15.797   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:29:15.798   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:30:15.833   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:30:15.833   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:30:15.834   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:31:15.873   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:31:15.873   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:31:15.874   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:32:15.918   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:32:15.918   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:32:15.918   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:33:16.005   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:33:16.005   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:33:16.005   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:34:16.039   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:34:16.040   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:34:16.040   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:35:16.079   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:35:16.080   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:35:16.080   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:36:16.116   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:36:16.116   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:36:16.116   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:37:16.153   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:37:16.153   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:37:16.154   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:38:16.268   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:38:16.268   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:38:16.269   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:39:16.312   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:39:16.312   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:39:16.312   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:40:16.359   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:40:16.360   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:40:16.360   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:41:16.404   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:41:16.404   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:41:16.405   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:42:16.447   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:42:16.448   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:42:16.448   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:43:16.555   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:43:16.556   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:43:16.556   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:44:16.589   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:44:16.590   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:44:16.590   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:45:16.624   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:45:16.625   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:45:16.626   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:46:16.660   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:46:16.661   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:46:16.661   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:47:16.697   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:47:16.698   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:47:16.698   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:48:16.777   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:48:16.778   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:48:16.778   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:49:16.817   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:49:16.818   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:49:16.818   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:50:16.862   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:50:16.863   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:50:16.863   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:51:16.909   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:51:16.909   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:51:16.910   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:52:16.960   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:52:16.960   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:52:16.960   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:53:17.023   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:53:17.023   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:53:17.024   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:54:17.058   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:54:17.058   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:54:17.059   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:55:17.105   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:55:17.106   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:55:17.106   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:56:17.138   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:56:17.139   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:56:17.139   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:57:17.172   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:57:17.172   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:57:17.173   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:58:17.268   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:58:17.268   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:58:17.269   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 00:59:17.309   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 00:59:17.309   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 00:59:17.310   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:00:17.342   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:00:17.342   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:00:17.343   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:01:17.370   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:01:17.371   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:01:17.371   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:02:17.410   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:02:17.410   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:02:17.411   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:03:17.906   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:03:17.906   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:03:17.907   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:04:17.951   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:04:17.951   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:04:17.952   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:05:17.995   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:05:17.996   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:05:17.996   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:06:18.040   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:06:18.041   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:06:18.041   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:07:18.084   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:07:18.085   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:07:18.085   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:08:18.163   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:08:18.163   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:08:18.164   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:09:18.202   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:09:18.202   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:09:18.203   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:10:18.237   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:10:18.237   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:10:18.238   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:11:18.286   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:11:18.286   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:11:18.287   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:12:18.332   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:12:18.332   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:12:18.333   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:13:18.476   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:13:18.476   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:13:18.476   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:14:18.516   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:14:18.517   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:14:18.517   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
2021-05-01 01:15:18.562   impfterminservice   [err] [impfstoffe_laden]   JSONDecodeError exception raised - retry 1
2021-05-01 01:15:18.563   impfterminservice   [err] [*  ]   File "C:\Users\Julius\anaconda3\envs\vaccipy\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-01 01:15:18.563   impfterminservice   [war] [*  ]   Erneuter Versuch in 60 Sekunden
